export const UPDATE_TASK_MODAL_TYPE = "UPDATE_TASK_MODAL_TYPE";
export const UPDATE_TASK_MODAL_VISIBLE = "UPDATE_TASK_MODAL_VISIBLE";
export const UPDATE_TASK_MODAL_DETAILS = "UPDATE_TASK_MODAL_DETAILS";
