export const UPDATE_MODAL_VISIBLE = "UPDATE_MODAL_VISIBLE";
export const UPDATE_MODAL_TITLE = "UPDATE_MODAL_TITLE";
export const UPDATE_MODAL_MESSAGE = "UPDATE_MODAL_MESSAGE";
export const UPDATE_MODAL_ICON_COLOR = "UPDATE_MODAL_ICON_COLOR";
